version: '2'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - kafka-test
  
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-test

#  kafka-hello-1:
#    image: kafka-hello
#    depends_on:
#      - kafka
#    ports:
#      - 8081:8083
#    environment:
#      KAFKA_HOST: kafka:9092
#    networks:
#      - kafka-test
#
#  kafka-hello-2:
#    image: kafka-hello
#    depends_on:
#      - kafka
#    ports:
#      - 8082:8083
#    environment:
#      KAFKA_HOST: kafka:9092
#    networks:
#      - kafka-test

networks:
  kafka-test:
    driver: bridge